version: 2
updates:
  # version updates for flutter's pub package manager
  - package-ecosystem: "pub"
    # Look for `pubspec.yaml` and `pubspec.lock` files in the `root` directory
    directory: "/"
    # Check the pub.dev registry for updates monthly
    schedule:
      interval: "monthly"
    # # default reviewers
    # reviewers:
    #   - "MarkisDev"