analyzer:
  errors:
    constant_identifier_names: ignore
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    prefer_single_quotes: true
    require_trailing_commas: true
    # lines_longer_than_80_chars: true
