List<Map<String, String>> cities = [
  {'city': 'Abidjan', 'country': 'Africa', 'timezone': 'GMT+00:00'},
  {'city': 'Accra', 'country': 'Africa', 'timezone': 'GMT+00:00'},
  {'city': 'Addis Ababa', 'country': 'Africa', 'timezone': 'GMT+03:00'},
  {'city': 'Algiers', 'country': 'Africa', 'timezone': 'GMT+01:00'},
  {'city': 'Asmara', 'country': 'Africa', 'timezone': 'GMT+03:00'},
  {'city': 'Asmera', 'country': 'Africa', 'timezone': 'GMT+03:00'},
  {'city': 'Bamako', 'country': 'Africa', 'timezone': 'GMT+00:00'},
  {'city': 'Bangui', 'country': 'Africa', 'timezone': 'GMT+01:00'},
  {'city': 'Banjul', 'country': 'Africa', 'timezone': 'GMT+00:00'},
  {'city': 'Bissau', 'country': 'Africa', 'timezone': 'GMT+00:00'},
  {'city': 'Blantyre', 'country': 'Africa', 'timezone': 'GMT+02:00'},
  {'city': 'Brazzaville', 'country': 'Africa', 'timezone': 'GMT+01:00'},
  {'city': 'Bujumbura', 'country': 'Africa', 'timezone': 'GMT+02:00'},
  {'city': 'Cairo', 'country': 'Africa', 'timezone': 'GMT+02:00'},
  {'city': 'Casablanca', 'country': 'Africa', 'timezone': 'GMT+00:00'},
  {'city': 'Ceuta', 'country': 'Africa', 'timezone': 'GMT+01:00'},
  {'city': 'Conakry', 'country': 'Africa', 'timezone': 'GMT+00:00'},
  {'city': 'Dakar', 'country': 'Africa', 'timezone': 'GMT+00:00'},
  {'city': 'Dar es Salaam', 'country': 'Africa', 'timezone': 'GMT+03:00'},
  {'city': 'Djibouti', 'country': 'Africa', 'timezone': 'GMT+03:00'},
  {'city': 'Douala', 'country': 'Africa', 'timezone': 'GMT+01:00'},
  {'city': 'El Aaiun', 'country': 'Africa', 'timezone': 'GMT+00:00'},
  {'city': 'Freetown', 'country': 'Africa', 'timezone': 'GMT+00:00'},
  {'city': 'Gaborone', 'country': 'Africa', 'timezone': 'GMT+02:00'},
  {'city': 'Harare', 'country': 'Africa', 'timezone': 'GMT+02:00'},
  {'city': 'Johannesburg', 'country': 'Africa', 'timezone': 'GMT+02:00'},
  {'city': 'Juba', 'country': 'Africa', 'timezone': 'GMT+02:00'},
  {'city': 'Kampala', 'country': 'Africa', 'timezone': 'GMT+03:00'},
  {'city': 'Khartoum', 'country': 'Africa', 'timezone': 'GMT+02:00'},
  {'city': 'Kigali', 'country': 'Africa', 'timezone': 'GMT+02:00'},
  {'city': 'Kinshasa', 'country': 'Africa', 'timezone': 'GMT+01:00'},
  {'city': 'Lagos', 'country': 'Africa', 'timezone': 'GMT+01:00'},
  {'city': 'Libreville', 'country': 'Africa', 'timezone': 'GMT+01:00'},
  {'city': 'Lome', 'country': 'Africa', 'timezone': 'GMT+00:00'},
  {'city': 'Luanda', 'country': 'Africa', 'timezone': 'GMT+01:00'},
  {'city': 'Lubumbashi', 'country': 'Africa', 'timezone': 'GMT+02:00'},
  {'city': 'Lusaka', 'country': 'Africa', 'timezone': 'GMT+02:00'},
  {'city': 'Malabo', 'country': 'Africa', 'timezone': 'GMT+01:00'},
  {'city': 'Maputo', 'country': 'Africa', 'timezone': 'GMT+02:00'},
  {'city': 'Maseru', 'country': 'Africa', 'timezone': 'GMT+02:00'},
  {'city': 'Mbabane', 'country': 'Africa', 'timezone': 'GMT+02:00'},
  {'city': 'Mogadishu', 'country': 'Africa', 'timezone': 'GMT+03:00'},
  {'city': 'Monrovia', 'country': 'Africa', 'timezone': 'GMT+00:00'},
  {'city': 'Nairobi', 'country': 'Africa', 'timezone': 'GMT+03:00'},
  {'city': 'Ndjamena', 'country': 'Africa', 'timezone': 'GMT+01:00'},
  {'city': 'Niamey', 'country': 'Africa', 'timezone': 'GMT+01:00'},
  {'city': 'Nouakchott', 'country': 'Africa', 'timezone': 'GMT+00:00'},
  {'city': 'Ouagadougou', 'country': 'Africa', 'timezone': 'GMT+00:00'},
  {'city': 'Porto-Novo', 'country': 'Africa', 'timezone': 'GMT+01:00'},
  {'city': 'Sao Tome', 'country': 'Africa', 'timezone': 'GMT+00:00'},
  {'city': 'Timbuktu', 'country': 'Africa', 'timezone': 'GMT+00:00'},
  {'city': 'Tripoli', 'country': 'Africa', 'timezone': 'GMT+02:00'},
  {'city': 'Tunis', 'country': 'Africa', 'timezone': 'GMT+01:00'},
  {'city': 'Windhoek', 'country': 'Africa', 'timezone': 'GMT+02:00'},
  {'city': 'Adak', 'country': 'America', 'timezone': 'GMT-09:00'},
  {'city': 'Anchorage', 'country': 'America', 'timezone': 'GMT-08:00'},
  {'city': 'Anguilla', 'country': 'America', 'timezone': 'GMT-04:00'},
  {'city': 'Antigua', 'country': 'America', 'timezone': 'GMT-04:00'},
  {'city': 'Araguaina', 'country': 'America', 'timezone': 'GMT-03:00'},
  {'city': 'America/Argentina/Buenos Aires', 'country': 'Unknown', 'timezone': 'GMT-03:00'},
  {'city': 'America/Argentina/Catamarca', 'country': 'Unknown', 'timezone': 'GMT-03:00'},
  {'city': 'America/Argentina/ComodRivadavia', 'country': 'Unknown', 'timezone': 'GMT-03:00'},
  {'city': 'America/Argentina/Cordoba', 'country': 'Unknown', 'timezone': 'GMT-03:00'},
  {'city': 'America/Argentina/Jujuy', 'country': 'Unknown', 'timezone': 'GMT-03:00'},
  {'city': 'America/Argentina/La Rioja', 'country': 'Unknown', 'timezone': 'GMT-03:00'},
  {'city': 'America/Argentina/Mendoza', 'country': 'Unknown', 'timezone': 'GMT-03:00'},
  {'city': 'America/Argentina/Rio Gallegos', 'country': 'Unknown', 'timezone': 'GMT-03:00'},
  {'city': 'America/Argentina/Salta', 'country': 'Unknown', 'timezone': 'GMT-03:00'},
  {'city': 'America/Argentina/San Juan', 'country': 'Unknown', 'timezone': 'GMT-03:00'},
  {'city': 'America/Argentina/San Luis', 'country': 'Unknown', 'timezone': 'GMT-03:00'},
  {'city': 'America/Argentina/Tucuman', 'country': 'Unknown', 'timezone': 'GMT-03:00'},
  {'city': 'America/Argentina/Ushuaia', 'country': 'Unknown', 'timezone': 'GMT-03:00'},
  {'city': 'Aruba', 'country': 'America', 'timezone': 'GMT-04:00'},
  {'city': 'Asuncion', 'country': 'America', 'timezone': 'GMT-03:00'},
  {'city': 'Atikokan', 'country': 'America', 'timezone': 'GMT-05:00'},
  {'city': 'Atka', 'country': 'America', 'timezone': 'GMT-09:00'},
  {'city': 'Bahia', 'country': 'America', 'timezone': 'GMT-03:00'},
  {'city': 'Bahia Banderas', 'country': 'America', 'timezone': 'GMT-06:00'},
  {'city': 'Barbados', 'country': 'America', 'timezone': 'GMT-04:00'},
  {'city': 'Belem', 'country': 'America', 'timezone': 'GMT-03:00'},
  {'city': 'Belize', 'country': 'America', 'timezone': 'GMT-06:00'},
  {'city': 'Blanc-Sablon', 'country': 'America', 'timezone': 'GMT-04:00'},
  {'city': 'Boa Vista', 'country': 'America', 'timezone': 'GMT-04:00'},
  {'city': 'Bogota', 'country': 'America', 'timezone': 'GMT-05:00'},
  {'city': 'Boise', 'country': 'America', 'timezone': 'GMT-06:00'},
  {'city': 'Buenos Aires', 'country': 'America', 'timezone': 'GMT-03:00'},
  {'city': 'Cambridge Bay', 'country': 'America', 'timezone': 'GMT-06:00'},
  {'city': 'Campo Grande', 'country': 'America', 'timezone': 'GMT-04:00'},
  {'city': 'Cancun', 'country': 'America', 'timezone': 'GMT-05:00'},
  {'city': 'Caracas', 'country': 'America', 'timezone': 'GMT-04:00'},
  {'city': 'Catamarca', 'country': 'America', 'timezone': 'GMT-03:00'},
  {'city': 'Cayenne', 'country': 'America', 'timezone': 'GMT-03:00'},
  {'city': 'Cayman', 'country': 'America', 'timezone': 'GMT-05:00'},
  {'city': 'Chicago', 'country': 'America', 'timezone': 'GMT-05:00'},
  {'city': 'Chihuahua', 'country': 'America', 'timezone': 'GMT-06:00'},
  {'city': 'Ciudad Juarez', 'country': 'America', 'timezone': 'GMT-06:00'},
  {'city': 'Coral Harbour', 'country': 'America', 'timezone': 'GMT-05:00'},
  {'city': 'Cordoba', 'country': 'America', 'timezone': 'GMT-03:00'},
  {'city': 'Costa Rica', 'country': 'America', 'timezone': 'GMT-06:00'},
  {'city': 'Creston', 'country': 'America', 'timezone': 'GMT-07:00'},
  {'city': 'Cuiaba', 'country': 'America', 'timezone': 'GMT-04:00'},
  {'city': 'Curacao', 'country': 'America', 'timezone': 'GMT-04:00'},
  {'city': 'Danmarkshavn', 'country': 'America', 'timezone': 'GMT+00:00'},
  {'city': 'Dawson', 'country': 'America', 'timezone': 'GMT-07:00'},
  {'city': 'Dawson Creek', 'country': 'America', 'timezone': 'GMT-07:00'},
  {'city': 'Denver', 'country': 'America', 'timezone': 'GMT-06:00'},
  {'city': 'Detroit', 'country': 'America', 'timezone': 'GMT-04:00'},
  {'city': 'Dominica', 'country': 'America', 'timezone': 'GMT-04:00'},
  {'city': 'Edmonton', 'country': 'America', 'timezone': 'GMT-06:00'},
  {'city': 'Eirunepe', 'country': 'America', 'timezone': 'GMT-05:00'},
  {'city': 'El Salvador', 'country': 'America', 'timezone': 'GMT-06:00'},
  {'city': 'Ensenada', 'country': 'America', 'timezone': 'GMT-07:00'},
  {'city': 'Fort Nelson', 'country': 'America', 'timezone': 'GMT-07:00'},
  {'city': 'Fort Wayne', 'country': 'America', 'timezone': 'GMT-04:00'},
  {'city': 'Fortaleza', 'country': 'America', 'timezone': 'GMT-03:00'},
  {'city': 'Glace Bay', 'country': 'America', 'timezone': 'GMT-03:00'},
  {'city': 'Godthab', 'country': 'America', 'timezone': 'GMT-02:00'},
  {'city': 'Goose Bay', 'country': 'America', 'timezone': 'GMT-03:00'},
  {'city': 'Grand Turk', 'country': 'America', 'timezone': 'GMT-04:00'},
  {'city': 'Grenada', 'country': 'America', 'timezone': 'GMT-04:00'},
  {'city': 'Guadeloupe', 'country': 'America', 'timezone': 'GMT-04:00'},
  {'city': 'Guatemala', 'country': 'America', 'timezone': 'GMT-06:00'},
  {'city': 'Guayaquil', 'country': 'America', 'timezone': 'GMT-05:00'},
  {'city': 'Guyana', 'country': 'America', 'timezone': 'GMT-04:00'},
  {'city': 'Halifax', 'country': 'America', 'timezone': 'GMT-03:00'},
  {'city': 'Havana', 'country': 'America', 'timezone': 'GMT-04:00'},
  {'city': 'Hermosillo', 'country': 'America', 'timezone': 'GMT-07:00'},
  {'city': 'America/Indiana/Indianapolis', 'country': 'Unknown', 'timezone': 'GMT-04:00'},
  {'city': 'America/Indiana/Knox', 'country': 'Unknown', 'timezone': 'GMT-05:00'},
  {'city': 'America/Indiana/Marengo', 'country': 'Unknown', 'timezone': 'GMT-04:00'},
  {'city': 'America/Indiana/Petersburg', 'country': 'Unknown', 'timezone': 'GMT-04:00'},
  {'city': 'America/Indiana/Tell City', 'country': 'Unknown', 'timezone': 'GMT-05:00'},
  {'city': 'America/Indiana/Vevay', 'country': 'Unknown', 'timezone': 'GMT-04:00'},
  {'city': 'America/Indiana/Vincennes', 'country': 'Unknown', 'timezone': 'GMT-04:00'},
  {'city': 'America/Indiana/Winamac', 'country': 'Unknown', 'timezone': 'GMT-04:00'},
  {'city': 'Indianapolis', 'country': 'America', 'timezone': 'GMT-04:00'},
  {'city': 'Inuvik', 'country': 'America', 'timezone': 'GMT-06:00'},
  {'city': 'Iqaluit', 'country': 'America', 'timezone': 'GMT-04:00'},
  {'city': 'Jamaica', 'country': 'America', 'timezone': 'GMT-05:00'},
  {'city': 'Jujuy', 'country': 'America', 'timezone': 'GMT-03:00'},
  {'city': 'Juneau', 'country': 'America', 'timezone': 'GMT-08:00'},
  {'city': 'America/Kentucky/Louisville', 'country': 'Unknown', 'timezone': 'GMT-04:00'},
  {'city': 'America/Kentucky/Monticello', 'country': 'Unknown', 'timezone': 'GMT-04:00'},
  {'city': 'Knox IN', 'country': 'America', 'timezone': 'GMT-05:00'},
  {'city': 'Kralendijk', 'country': 'America', 'timezone': 'GMT-04:00'},
  {'city': 'La Paz', 'country': 'America', 'timezone': 'GMT-04:00'},
  {'city': 'Lima', 'country': 'America', 'timezone': 'GMT-05:00'},
  {'city': 'Los Angeles', 'country': 'America', 'timezone': 'GMT-07:00'},
  {'city': 'Louisville', 'country': 'America', 'timezone': 'GMT-04:00'},
  {'city': 'Lower Princes', 'country': 'America', 'timezone': 'GMT-04:00'},
  {'city': 'Maceio', 'country': 'America', 'timezone': 'GMT-03:00'},
  {'city': 'Managua', 'country': 'America', 'timezone': 'GMT-06:00'},
  {'city': 'Manaus', 'country': 'America', 'timezone': 'GMT-04:00'},
  {'city': 'Marigot', 'country': 'America', 'timezone': 'GMT-04:00'},
  {'city': 'Martinique', 'country': 'America', 'timezone': 'GMT-04:00'},
  {'city': 'Matamoros', 'country': 'America', 'timezone': 'GMT-05:00'},
  {'city': 'Mazatlan', 'country': 'America', 'timezone': 'GMT-07:00'},
  {'city': 'Mendoza', 'country': 'America', 'timezone': 'GMT-03:00'},
  {'city': 'Menominee', 'country': 'America', 'timezone': 'GMT-05:00'},
  {'city': 'Merida', 'country': 'America', 'timezone': 'GMT-06:00'},
  {'city': 'Metlakatla', 'country': 'America', 'timezone': 'GMT-08:00'},
  {'city': 'Mexico City', 'country': 'America', 'timezone': 'GMT-06:00'},
  {'city': 'Miquelon', 'country': 'America', 'timezone': 'GMT-02:00'},
  {'city': 'Moncton', 'country': 'America', 'timezone': 'GMT-03:00'},
  {'city': 'Monterrey', 'country': 'America', 'timezone': 'GMT-06:00'},
  {'city': 'Montevideo', 'country': 'America', 'timezone': 'GMT-03:00'},
  {'city': 'Montreal', 'country': 'America', 'timezone': 'GMT-04:00'},
  {'city': 'Montserrat', 'country': 'America', 'timezone': 'GMT-04:00'},
  {'city': 'Nassau', 'country': 'America', 'timezone': 'GMT-04:00'},
  {'city': 'New York', 'country': 'America', 'timezone': 'GMT-04:00'},
  {'city': 'Nipigon', 'country': 'America', 'timezone': 'GMT-04:00'},
  {'city': 'Nome', 'country': 'America', 'timezone': 'GMT-08:00'},
  {'city': 'Noronha', 'country': 'America', 'timezone': 'GMT-02:00'},
  {'city': 'America/North Dakota/Beulah', 'country': 'Unknown', 'timezone': 'GMT-05:00'},
  {'city': 'America/North Dakota/Center', 'country': 'Unknown', 'timezone': 'GMT-05:00'},
  {'city': 'America/North Dakota/New Salem', 'country': 'Unknown', 'timezone': 'GMT-05:00'},
  {'city': 'Nuuk', 'country': 'America', 'timezone': 'GMT-02:00'},
  {'city': 'Ojinaga', 'country': 'America', 'timezone': 'GMT-05:00'},
  {'city': 'Panama', 'country': 'America', 'timezone': 'GMT-05:00'},
  {'city': 'Pangnirtung', 'country': 'America', 'timezone': 'GMT-04:00'},
  {'city': 'Paramaribo', 'country': 'America', 'timezone': 'GMT-03:00'},
  {'city': 'Phoenix', 'country': 'America', 'timezone': 'GMT-07:00'},
  {'city': 'Port-au-Prince', 'country': 'America', 'timezone': 'GMT-04:00'},
  {'city': 'Port of Spain', 'country': 'America', 'timezone': 'GMT-04:00'},
  {'city': 'Porto Acre', 'country': 'America', 'timezone': 'GMT-05:00'},
  {'city': 'Porto Velho', 'country': 'America', 'timezone': 'GMT-04:00'},
  {'city': 'Puerto Rico', 'country': 'America', 'timezone': 'GMT-04:00'},
  {'city': 'Punta Arenas', 'country': 'America', 'timezone': 'GMT-03:00'},
  {'city': 'Rainy River', 'country': 'America', 'timezone': 'GMT-05:00'},
  {'city': 'Rankin Inlet', 'country': 'America', 'timezone': 'GMT-05:00'},
  {'city': 'Recife', 'country': 'America', 'timezone': 'GMT-03:00'},
  {'city': 'Regina', 'country': 'America', 'timezone': 'GMT-06:00'},
  {'city': 'Resolute', 'country': 'America', 'timezone': 'GMT-05:00'},
  {'city': 'Rio Branco', 'country': 'America', 'timezone': 'GMT-05:00'},
  {'city': 'Rosario', 'country': 'America', 'timezone': 'GMT-03:00'},
  {'city': 'Santa Isabel', 'country': 'America', 'timezone': 'GMT-07:00'},
  {'city': 'Santarem', 'country': 'America', 'timezone': 'GMT-03:00'},
  {'city': 'Santiago', 'country': 'America', 'timezone': 'GMT-03:00'},
  {'city': 'Santo Domingo', 'country': 'America', 'timezone': 'GMT-04:00'},
  {'city': 'Sao Paulo', 'country': 'America', 'timezone': 'GMT-03:00'},
  {'city': 'Scoresbysund', 'country': 'America', 'timezone': 'GMT-02:00'},
  {'city': 'Shiprock', 'country': 'America', 'timezone': 'GMT-06:00'},
  {'city': 'Sitka', 'country': 'America', 'timezone': 'GMT-08:00'},
  {'city': 'St Barthelemy', 'country': 'America', 'timezone': 'GMT-04:00'},
  {'city': 'St Johns', 'country': 'America', 'timezone': 'GMT-02:30'},
  {'city': 'St Kitts', 'country': 'America', 'timezone': 'GMT-04:00'},
  {'city': 'St Lucia', 'country': 'America', 'timezone': 'GMT-04:00'},
  {'city': 'St Thomas', 'country': 'America', 'timezone': 'GMT-04:00'},
  {'city': 'St Vincent', 'country': 'America', 'timezone': 'GMT-04:00'},
  {'city': 'Swift Current', 'country': 'America', 'timezone': 'GMT-06:00'},
  {'city': 'Tegucigalpa', 'country': 'America', 'timezone': 'GMT-06:00'},
  {'city': 'Thule', 'country': 'America', 'timezone': 'GMT-03:00'},
  {'city': 'Thunder Bay', 'country': 'America', 'timezone': 'GMT-04:00'},
  {'city': 'Tijuana', 'country': 'America', 'timezone': 'GMT-07:00'},
  {'city': 'Toronto', 'country': 'America', 'timezone': 'GMT-04:00'},
  {'city': 'Tortola', 'country': 'America', 'timezone': 'GMT-04:00'},
  {'city': 'Vancouver', 'country': 'America', 'timezone': 'GMT-07:00'},
  {'city': 'Virgin', 'country': 'America', 'timezone': 'GMT-04:00'},
  {'city': 'Whitehorse', 'country': 'America', 'timezone': 'GMT-07:00'},
  {'city': 'Winnipeg', 'country': 'America', 'timezone': 'GMT-05:00'},
  {'city': 'Yakutat', 'country': 'America', 'timezone': 'GMT-08:00'},
  {'city': 'Yellowknife', 'country': 'America', 'timezone': 'GMT-06:00'},
  {'city': 'Casey', 'country': 'Antarctica', 'timezone': 'GMT+08:00'},
  {'city': 'Davis', 'country': 'Antarctica', 'timezone': 'GMT+07:00'},
  {'city': 'DumontDUrville', 'country': 'Antarctica', 'timezone': 'GMT+10:00'},
  {'city': 'Macquarie', 'country': 'Antarctica', 'timezone': 'GMT+11:00'},
  {'city': 'Mawson', 'country': 'Antarctica', 'timezone': 'GMT+05:00'},
  {'city': 'McMurdo', 'country': 'Antarctica', 'timezone': 'GMT+13:00'},
  {'city': 'Palmer', 'country': 'Antarctica', 'timezone': 'GMT-03:00'},
  {'city': 'Rothera', 'country': 'Antarctica', 'timezone': 'GMT-03:00'},
  {'city': 'South Pole', 'country': 'Antarctica', 'timezone': 'GMT+13:00'},
  {'city': 'Syowa', 'country': 'Antarctica', 'timezone': 'GMT+03:00'},
  {'city': 'Troll', 'country': 'Antarctica', 'timezone': 'GMT+00:00'},
  {'city': 'Vostok', 'country': 'Antarctica', 'timezone': 'GMT+05:00'},
  {'city': 'Longyearbyen', 'country': 'Arctic', 'timezone': 'GMT+01:00'},
  {'city': 'Aden', 'country': 'Asia', 'timezone': 'GMT+03:00'},
  {'city': 'Almaty', 'country': 'Asia', 'timezone': 'GMT+05:00'},
  {'city': 'Amman', 'country': 'Asia', 'timezone': 'GMT+03:00'},
  {'city': 'Anadyr', 'country': 'Asia', 'timezone': 'GMT+12:00'},
  {'city': 'Aqtau', 'country': 'Asia', 'timezone': 'GMT+05:00'},
  {'city': 'Aqtobe', 'country': 'Asia', 'timezone': 'GMT+05:00'},
  {'city': 'Ashgabat', 'country': 'Asia', 'timezone': 'GMT+05:00'},
  {'city': 'Ashkhabad', 'country': 'Asia', 'timezone': 'GMT+05:00'},
  {'city': 'Atyrau', 'country': 'Asia', 'timezone': 'GMT+05:00'},
  {'city': 'Baghdad', 'country': 'Asia', 'timezone': 'GMT+03:00'},
  {'city': 'Bahrain', 'country': 'Asia', 'timezone': 'GMT+03:00'},
  {'city': 'Baku', 'country': 'Asia', 'timezone': 'GMT+04:00'},
  {'city': 'Bangkok', 'country': 'Asia', 'timezone': 'GMT+07:00'},
  {'city': 'Barnaul', 'country': 'Asia', 'timezone': 'GMT+07:00'},
  {'city': 'Beirut', 'country': 'Asia', 'timezone': 'GMT+02:00'},
  {'city': 'Bishkek', 'country': 'Asia', 'timezone': 'GMT+06:00'},
  {'city': 'Brunei', 'country': 'Asia', 'timezone': 'GMT+08:00'},
  {'city': 'Calcutta', 'country': 'Asia', 'timezone': 'GMT+05:30'},
  {'city': 'Chita', 'country': 'Asia', 'timezone': 'GMT+09:00'},
  {'city': 'Choibalsan', 'country': 'Asia', 'timezone': 'GMT+08:00'},
  {'city': 'Chongqing', 'country': 'Asia', 'timezone': 'GMT+08:00'},
  {'city': 'Chungking', 'country': 'Asia', 'timezone': 'GMT+08:00'},
  {'city': 'Colombo', 'country': 'Asia', 'timezone': 'GMT+05:30'},
  {'city': 'Dacca', 'country': 'Asia', 'timezone': 'GMT+06:00'},
  {'city': 'Damascus', 'country': 'Asia', 'timezone': 'GMT+03:00'},
  {'city': 'Dhaka', 'country': 'Asia', 'timezone': 'GMT+06:00'},
  {'city': 'Dili', 'country': 'Asia', 'timezone': 'GMT+09:00'},
  {'city': 'Dubai', 'country': 'Asia', 'timezone': 'GMT+04:00'},
  {'city': 'Dushanbe', 'country': 'Asia', 'timezone': 'GMT+05:00'},
  {'city': 'Famagusta', 'country': 'Asia', 'timezone': 'GMT+02:00'},
  {'city': 'Gaza', 'country': 'Asia', 'timezone': 'GMT+02:00'},
  {'city': 'Harbin', 'country': 'Asia', 'timezone': 'GMT+08:00'},
  {'city': 'Hebron', 'country': 'Asia', 'timezone': 'GMT+02:00'},
  {'city': 'Ho Chi Minh', 'country': 'Asia', 'timezone': 'GMT+07:00'},
  {'city': 'Hong Kong', 'country': 'Asia', 'timezone': 'GMT+08:00'},
  {'city': 'Hovd', 'country': 'Asia', 'timezone': 'GMT+07:00'},
  {'city': 'Irkutsk', 'country': 'Asia', 'timezone': 'GMT+08:00'},
  {'city': 'Istanbul', 'country': 'Asia', 'timezone': 'GMT+03:00'},
  {'city': 'Jakarta', 'country': 'Asia', 'timezone': 'GMT+07:00'},
  {'city': 'Jayapura', 'country': 'Asia', 'timezone': 'GMT+09:00'},
  {'city': 'Jerusalem', 'country': 'Asia', 'timezone': 'GMT+02:00'},
  {'city': 'Kabul', 'country': 'Asia', 'timezone': 'GMT+04:30'},
  {'city': 'Kamchatka', 'country': 'Asia', 'timezone': 'GMT+12:00'},
  {'city': 'Karachi', 'country': 'Asia', 'timezone': 'GMT+05:00'},
  {'city': 'Kashgar', 'country': 'Asia', 'timezone': 'GMT+06:00'},
  {'city': 'Kathmandu', 'country': 'Asia', 'timezone': 'GMT+05:45'},
  {'city': 'Katmandu', 'country': 'Asia', 'timezone': 'GMT+05:45'},
  {'city': 'Khandyga', 'country': 'Asia', 'timezone': 'GMT+09:00'},
  {'city': 'Kolkata', 'country': 'Asia', 'timezone': 'GMT+05:30'},
  {'city': 'Krasnoyarsk', 'country': 'Asia', 'timezone': 'GMT+07:00'},
  {'city': 'Kuala Lumpur', 'country': 'Asia', 'timezone': 'GMT+08:00'},
  {'city': 'Kuching', 'country': 'Asia', 'timezone': 'GMT+08:00'},
  {'city': 'Kuwait', 'country': 'Asia', 'timezone': 'GMT+03:00'},
  {'city': 'Macao', 'country': 'Asia', 'timezone': 'GMT+08:00'},
  {'city': 'Macau', 'country': 'Asia', 'timezone': 'GMT+08:00'},
  {'city': 'Magadan', 'country': 'Asia', 'timezone': 'GMT+11:00'},
  {'city': 'Makassar', 'country': 'Asia', 'timezone': 'GMT+08:00'},
  {'city': 'Manila', 'country': 'Asia', 'timezone': 'GMT+08:00'},
  {'city': 'Muscat', 'country': 'Asia', 'timezone': 'GMT+04:00'},
  {'city': 'Nicosia', 'country': 'Asia', 'timezone': 'GMT+02:00'},
  {'city': 'Novokuznetsk', 'country': 'Asia', 'timezone': 'GMT+07:00'},
  {'city': 'Novosibirsk', 'country': 'Asia', 'timezone': 'GMT+07:00'},
  {'city': 'Omsk', 'country': 'Asia', 'timezone': 'GMT+06:00'},
  {'city': 'Oral', 'country': 'Asia', 'timezone': 'GMT+05:00'},
  {'city': 'Phnom Penh', 'country': 'Asia', 'timezone': 'GMT+07:00'},
  {'city': 'Pontianak', 'country': 'Asia', 'timezone': 'GMT+07:00'},
  {'city': 'Pyongyang', 'country': 'Asia', 'timezone': 'GMT+09:00'},
  {'city': 'Qatar', 'country': 'Asia', 'timezone': 'GMT+03:00'},
  {'city': 'Qostanay', 'country': 'Asia', 'timezone': 'GMT+05:00'},
  {'city': 'Qyzylorda', 'country': 'Asia', 'timezone': 'GMT+05:00'},
  {'city': 'Rangoon', 'country': 'Asia', 'timezone': 'GMT+06:30'},
  {'city': 'Riyadh', 'country': 'Asia', 'timezone': 'GMT+03:00'},
  {'city': 'Saigon', 'country': 'Asia', 'timezone': 'GMT+07:00'},
  {'city': 'Sakhalin', 'country': 'Asia', 'timezone': 'GMT+11:00'},
  {'city': 'Samarkand', 'country': 'Asia', 'timezone': 'GMT+05:00'},
  {'city': 'Seoul', 'country': 'Asia', 'timezone': 'GMT+09:00'},
  {'city': 'Shanghai', 'country': 'Asia', 'timezone': 'GMT+08:00'},
  {'city': 'Singapore', 'country': 'Asia', 'timezone': 'GMT+08:00'},
  {'city': 'Srednekolymsk', 'country': 'Asia', 'timezone': 'GMT+11:00'},
  {'city': 'Taipei', 'country': 'Asia', 'timezone': 'GMT+08:00'},
  {'city': 'Tashkent', 'country': 'Asia', 'timezone': 'GMT+05:00'},
  {'city': 'Tbilisi', 'country': 'Asia', 'timezone': 'GMT+04:00'},
  {'city': 'Tehran', 'country': 'Asia', 'timezone': 'GMT+03:30'},
  {'city': 'Tel Aviv', 'country': 'Asia', 'timezone': 'GMT+02:00'},
  {'city': 'Thimbu', 'country': 'Asia', 'timezone': 'GMT+06:00'},
  {'city': 'Thimphu', 'country': 'Asia', 'timezone': 'GMT+06:00'},
  {'city': 'Tokyo', 'country': 'Asia', 'timezone': 'GMT+09:00'},
  {'city': 'Tomsk', 'country': 'Asia', 'timezone': 'GMT+07:00'},
  {'city': 'Ujung Pandang', 'country': 'Asia', 'timezone': 'GMT+08:00'},
  {'city': 'Ulaanbaatar', 'country': 'Asia', 'timezone': 'GMT+08:00'},
  {'city': 'Ulan Bator', 'country': 'Asia', 'timezone': 'GMT+08:00'},
  {'city': 'Urumqi', 'country': 'Asia', 'timezone': 'GMT+06:00'},
  {'city': 'Ust-Nera', 'country': 'Asia', 'timezone': 'GMT+10:00'},
  {'city': 'Vientiane', 'country': 'Asia', 'timezone': 'GMT+07:00'},
  {'city': 'Vladivostok', 'country': 'Asia', 'timezone': 'GMT+10:00'},
  {'city': 'Yakutsk', 'country': 'Asia', 'timezone': 'GMT+09:00'},
  {'city': 'Yangon', 'country': 'Asia', 'timezone': 'GMT+06:30'},
  {'city': 'Yekaterinburg', 'country': 'Asia', 'timezone': 'GMT+05:00'},
  {'city': 'Yerevan', 'country': 'Asia', 'timezone': 'GMT+04:00'},
  {'city': 'Azores', 'country': 'Atlantic', 'timezone': 'GMT-01:00'},
  {'city': 'Bermuda', 'country': 'Atlantic', 'timezone': 'GMT-03:00'},
  {'city': 'Canary', 'country': 'Atlantic', 'timezone': 'GMT+00:00'},
  {'city': 'Cape Verde', 'country': 'Atlantic', 'timezone': 'GMT-01:00'},
  {'city': 'Faeroe', 'country': 'Atlantic', 'timezone': 'GMT+00:00'},
  {'city': 'Faroe', 'country': 'Atlantic', 'timezone': 'GMT+00:00'},
  {'city': 'Jan Mayen', 'country': 'Atlantic', 'timezone': 'GMT+01:00'},
  {'city': 'Madeira', 'country': 'Atlantic', 'timezone': 'GMT+00:00'},
  {'city': 'Reykjavik', 'country': 'Atlantic', 'timezone': 'GMT+00:00'},
  {'city': 'South Georgia', 'country': 'Atlantic', 'timezone': 'GMT-02:00'},
  {'city': 'St Helena', 'country': 'Atlantic', 'timezone': 'GMT+00:00'},
  {'city': 'Stanley', 'country': 'Atlantic', 'timezone': 'GMT-03:00'},
  {'city': 'ACT', 'country': 'Australia', 'timezone': 'GMT+11:00'},
  {'city': 'Adelaide', 'country': 'Australia', 'timezone': 'GMT+10:30'},
  {'city': 'Brisbane', 'country': 'Australia', 'timezone': 'GMT+10:00'},
  {'city': 'Broken Hill', 'country': 'Australia', 'timezone': 'GMT+10:30'},
  {'city': 'Canberra', 'country': 'Australia', 'timezone': 'GMT+11:00'},
  {'city': 'Currie', 'country': 'Australia', 'timezone': 'GMT+11:00'},
  {'city': 'Darwin', 'country': 'Australia', 'timezone': 'GMT+09:30'},
  {'city': 'Eucla', 'country': 'Australia', 'timezone': 'GMT+08:45'},
  {'city': 'Hobart', 'country': 'Australia', 'timezone': 'GMT+11:00'},
  {'city': 'LHI', 'country': 'Australia', 'timezone': 'GMT+11:00'},
  {'city': 'Lindeman', 'country': 'Australia', 'timezone': 'GMT+10:00'},
  {'city': 'Lord Howe', 'country': 'Australia', 'timezone': 'GMT+11:00'},
  {'city': 'Melbourne', 'country': 'Australia', 'timezone': 'GMT+11:00'},
  {'city': 'NSW', 'country': 'Australia', 'timezone': 'GMT+11:00'},
  {'city': 'North', 'country': 'Australia', 'timezone': 'GMT+09:30'},
  {'city': 'Perth', 'country': 'Australia', 'timezone': 'GMT+08:00'},
  {'city': 'Queensland', 'country': 'Australia', 'timezone': 'GMT+10:00'},
  {'city': 'South', 'country': 'Australia', 'timezone': 'GMT+10:30'},
  {'city': 'Sydney', 'country': 'Australia', 'timezone': 'GMT+11:00'},
  {'city': 'Tasmania', 'country': 'Australia', 'timezone': 'GMT+11:00'},
  {'city': 'Victoria', 'country': 'Australia', 'timezone': 'GMT+11:00'},
  {'city': 'West', 'country': 'Australia', 'timezone': 'GMT+08:00'},
  {'city': 'Yancowinna', 'country': 'Australia', 'timezone': 'GMT+10:30'},
  {'city': 'Acre', 'country': 'Brazil', 'timezone': 'GMT-05:00'},
  {'city': 'DeNoronha', 'country': 'Brazil', 'timezone': 'GMT-02:00'},
  {'city': 'East', 'country': 'Brazil', 'timezone': 'GMT-03:00'},
  {'city': 'West', 'country': 'Brazil', 'timezone': 'GMT-04:00'},
  {'city': 'CET', 'country': 'Unknown', 'timezone': 'GMT+01:00'},
  {'city': 'CST6CDT', 'country': 'Unknown', 'timezone': 'GMT-05:00'},
  {'city': 'Atlantic', 'country': 'Canada', 'timezone': 'GMT-03:00'},
  {'city': 'Central', 'country': 'Canada', 'timezone': 'GMT-05:00'},
  {'city': 'Eastern', 'country': 'Canada', 'timezone': 'GMT-04:00'},
  {'city': 'Mountain', 'country': 'Canada', 'timezone': 'GMT-06:00'},
  {'city': 'Newfoundland', 'country': 'Canada', 'timezone': 'GMT-02:30'},
  {'city': 'Pacific', 'country': 'Canada', 'timezone': 'GMT-07:00'},
  {'city': 'Saskatchewan', 'country': 'Canada', 'timezone': 'GMT-06:00'},
  {'city': 'Yukon', 'country': 'Canada', 'timezone': 'GMT-07:00'},
  {'city': 'Continental', 'country': 'Chile', 'timezone': 'GMT-03:00'},
  {'city': 'EasterIsland', 'country': 'Chile', 'timezone': 'GMT-05:00'},
  {'city': 'Cuba', 'country': 'Unknown', 'timezone': 'GMT-04:00'},
  {'city': 'EET', 'country': 'Unknown', 'timezone': 'GMT+02:00'},
  {'city': 'EST', 'country': 'Unknown', 'timezone': 'GMT-05:00'},
  {'city': 'EST5EDT', 'country': 'Unknown', 'timezone': 'GMT-04:00'},
  {'city': 'Egypt', 'country': 'Unknown', 'timezone': 'GMT+02:00'},
  {'city': 'Eire', 'country': 'Unknown', 'timezone': 'GMT+00:00'},
  {'city': 'GMT', 'country': 'Etc', 'timezone': 'GMT+00:00'},
  {'city': 'GMT+0', 'country': 'Etc', 'timezone': 'GMT+00:00'},
  {'city': 'GMT+1', 'country': 'Etc', 'timezone': 'GMT-01:00'},
  {'city': 'GMT+10', 'country': 'Etc', 'timezone': 'GMT-10:00'},
  {'city': 'GMT+11', 'country': 'Etc', 'timezone': 'GMT-11:00'},
  {'city': 'GMT+12', 'country': 'Etc', 'timezone': 'GMT-12:00'},
  {'city': 'GMT+2', 'country': 'Etc', 'timezone': 'GMT-02:00'},
  {'city': 'GMT+3', 'country': 'Etc', 'timezone': 'GMT-03:00'},
  {'city': 'GMT+4', 'country': 'Etc', 'timezone': 'GMT-04:00'},
  {'city': 'GMT+5', 'country': 'Etc', 'timezone': 'GMT-05:00'},
  {'city': 'GMT+6', 'country': 'Etc', 'timezone': 'GMT-06:00'},
  {'city': 'GMT+7', 'country': 'Etc', 'timezone': 'GMT-07:00'},
  {'city': 'GMT+8', 'country': 'Etc', 'timezone': 'GMT-08:00'},
  {'city': 'GMT+9', 'country': 'Etc', 'timezone': 'GMT-09:00'},
  {'city': 'GMT-0', 'country': 'Etc', 'timezone': 'GMT+00:00'},
  {'city': 'GMT-1', 'country': 'Etc', 'timezone': 'GMT+01:00'},
  {'city': 'GMT-10', 'country': 'Etc', 'timezone': 'GMT+10:00'},
  {'city': 'GMT-11', 'country': 'Etc', 'timezone': 'GMT+11:00'},
  {'city': 'GMT-12', 'country': 'Etc', 'timezone': 'GMT+12:00'},
  {'city': 'GMT-13', 'country': 'Etc', 'timezone': 'GMT+13:00'},
  {'city': 'GMT-14', 'country': 'Etc', 'timezone': 'GMT+14:00'},
  {'city': 'GMT-2', 'country': 'Etc', 'timezone': 'GMT+02:00'},
  {'city': 'GMT-3', 'country': 'Etc', 'timezone': 'GMT+03:00'},
  {'city': 'GMT-4', 'country': 'Etc', 'timezone': 'GMT+04:00'},
  {'city': 'GMT-5', 'country': 'Etc', 'timezone': 'GMT+05:00'},
  {'city': 'GMT-6', 'country': 'Etc', 'timezone': 'GMT+06:00'},
  {'city': 'GMT-7', 'country': 'Etc', 'timezone': 'GMT+07:00'},
  {'city': 'GMT-8', 'country': 'Etc', 'timezone': 'GMT+08:00'},
  {'city': 'GMT-9', 'country': 'Etc', 'timezone': 'GMT+09:00'},
  {'city': 'GMT0', 'country': 'Etc', 'timezone': 'GMT+00:00'},
  {'city': 'Greenwich', 'country': 'Etc', 'timezone': 'GMT+00:00'},
  {'city': 'UCT', 'country': 'Etc', 'timezone': 'GMT+00:00'},
  {'city': 'UTC', 'country': 'Etc', 'timezone': 'GMT+00:00'},
  {'city': 'Universal', 'country': 'Etc', 'timezone': 'GMT+00:00'},
  {'city': 'Zulu', 'country': 'Etc', 'timezone': 'GMT+00:00'},
  {'city': 'Amsterdam', 'country': 'Europe', 'timezone': 'GMT+01:00'},
  {'city': 'Andorra', 'country': 'Europe', 'timezone': 'GMT+01:00'},
  {'city': 'Astrakhan', 'country': 'Europe', 'timezone': 'GMT+04:00'},
  {'city': 'Athens', 'country': 'Europe', 'timezone': 'GMT+02:00'},
  {'city': 'Belfast', 'country': 'Europe', 'timezone': 'GMT+00:00'},
  {'city': 'Belgrade', 'country': 'Europe', 'timezone': 'GMT+01:00'},
  {'city': 'Berlin', 'country': 'Europe', 'timezone': 'GMT+01:00'},
  {'city': 'Bratislava', 'country': 'Europe', 'timezone': 'GMT+01:00'},
  {'city': 'Brussels', 'country': 'Europe', 'timezone': 'GMT+01:00'},
  {'city': 'Bucharest', 'country': 'Europe', 'timezone': 'GMT+02:00'},
  {'city': 'Budapest', 'country': 'Europe', 'timezone': 'GMT+01:00'},
  {'city': 'Busingen', 'country': 'Europe', 'timezone': 'GMT+01:00'},
  {'city': 'Chisinau', 'country': 'Europe', 'timezone': 'GMT+02:00'},
  {'city': 'Copenhagen', 'country': 'Europe', 'timezone': 'GMT+01:00'},
  {'city': 'Dublin', 'country': 'Europe', 'timezone': 'GMT+00:00'},
  {'city': 'Gibraltar', 'country': 'Europe', 'timezone': 'GMT+01:00'},
  {'city': 'Guernsey', 'country': 'Europe', 'timezone': 'GMT+00:00'},
  {'city': 'Helsinki', 'country': 'Europe', 'timezone': 'GMT+02:00'},
  {'city': 'Isle of Man', 'country': 'Europe', 'timezone': 'GMT+00:00'},
  {'city': 'Istanbul', 'country': 'Europe', 'timezone': 'GMT+03:00'},
  {'city': 'Jersey', 'country': 'Europe', 'timezone': 'GMT+00:00'},
  {'city': 'Kaliningrad', 'country': 'Europe', 'timezone': 'GMT+02:00'},
  {'city': 'Kiev', 'country': 'Europe', 'timezone': 'GMT+02:00'},
  {'city': 'Kirov', 'country': 'Europe', 'timezone': 'GMT+03:00'},
  {'city': 'Kyiv', 'country': 'Europe', 'timezone': 'GMT+02:00'},
  {'city': 'Lisbon', 'country': 'Europe', 'timezone': 'GMT+00:00'},
  {'city': 'Ljubljana', 'country': 'Europe', 'timezone': 'GMT+01:00'},
  {'city': 'London', 'country': 'Europe', 'timezone': 'GMT+00:00'},
  {'city': 'Luxembourg', 'country': 'Europe', 'timezone': 'GMT+01:00'},
  {'city': 'Madrid', 'country': 'Europe', 'timezone': 'GMT+01:00'},
  {'city': 'Malta', 'country': 'Europe', 'timezone': 'GMT+01:00'},
  {'city': 'Mariehamn', 'country': 'Europe', 'timezone': 'GMT+02:00'},
  {'city': 'Minsk', 'country': 'Europe', 'timezone': 'GMT+03:00'},
  {'city': 'Monaco', 'country': 'Europe', 'timezone': 'GMT+01:00'},
  {'city': 'Moscow', 'country': 'Europe', 'timezone': 'GMT+03:00'},
  {'city': 'Nicosia', 'country': 'Europe', 'timezone': 'GMT+02:00'},
  {'city': 'Oslo', 'country': 'Europe', 'timezone': 'GMT+01:00'},
  {'city': 'Paris', 'country': 'Europe', 'timezone': 'GMT+01:00'},
  {'city': 'Podgorica', 'country': 'Europe', 'timezone': 'GMT+01:00'},
  {'city': 'Prague', 'country': 'Europe', 'timezone': 'GMT+01:00'},
  {'city': 'Riga', 'country': 'Europe', 'timezone': 'GMT+02:00'},
  {'city': 'Rome', 'country': 'Europe', 'timezone': 'GMT+01:00'},
  {'city': 'Samara', 'country': 'Europe', 'timezone': 'GMT+04:00'},
  {'city': 'San Marino', 'country': 'Europe', 'timezone': 'GMT+01:00'},
  {'city': 'Sarajevo', 'country': 'Europe', 'timezone': 'GMT+01:00'},
  {'city': 'Saratov', 'country': 'Europe', 'timezone': 'GMT+04:00'},
  {'city': 'Simferopol', 'country': 'Europe', 'timezone': 'GMT+03:00'},
  {'city': 'Skopje', 'country': 'Europe', 'timezone': 'GMT+01:00'},
  {'city': 'Sofia', 'country': 'Europe', 'timezone': 'GMT+02:00'},
  {'city': 'Stockholm', 'country': 'Europe', 'timezone': 'GMT+01:00'},
  {'city': 'Tallinn', 'country': 'Europe', 'timezone': 'GMT+02:00'},
  {'city': 'Tirane', 'country': 'Europe', 'timezone': 'GMT+01:00'},
  {'city': 'Tiraspol', 'country': 'Europe', 'timezone': 'GMT+02:00'},
  {'city': 'Ulyanovsk', 'country': 'Europe', 'timezone': 'GMT+04:00'},
  {'city': 'Uzhgorod', 'country': 'Europe', 'timezone': 'GMT+02:00'},
  {'city': 'Vaduz', 'country': 'Europe', 'timezone': 'GMT+01:00'},
  {'city': 'Vatican', 'country': 'Europe', 'timezone': 'GMT+01:00'},
  {'city': 'Vienna', 'country': 'Europe', 'timezone': 'GMT+01:00'},
  {'city': 'Vilnius', 'country': 'Europe', 'timezone': 'GMT+02:00'},
  {'city': 'Volgograd', 'country': 'Europe', 'timezone': 'GMT+03:00'},
  {'city': 'Warsaw', 'country': 'Europe', 'timezone': 'GMT+01:00'},
  {'city': 'Zagreb', 'country': 'Europe', 'timezone': 'GMT+01:00'},
  {'city': 'Zaporozhye', 'country': 'Europe', 'timezone': 'GMT+02:00'},
  {'city': 'Zurich', 'country': 'Europe', 'timezone': 'GMT+01:00'},
  {'city': 'GB', 'country': 'Unknown', 'timezone': 'GMT+00:00'},
  {'city': 'GB-Eire', 'country': 'Unknown', 'timezone': 'GMT+00:00'},
  {'city': 'GMT', 'country': 'Unknown', 'timezone': 'GMT+00:00'},
  {'city': 'GMT+0', 'country': 'Unknown', 'timezone': 'GMT+00:00'},
  {'city': 'GMT-0', 'country': 'Unknown', 'timezone': 'GMT+00:00'},
  {'city': 'GMT0', 'country': 'Unknown', 'timezone': 'GMT+00:00'},
  {'city': 'Greenwich', 'country': 'Unknown', 'timezone': 'GMT+00:00'},
  {'city': 'HST', 'country': 'Unknown', 'timezone': 'GMT-10:00'},
  {'city': 'Hongkong', 'country': 'Unknown', 'timezone': 'GMT+08:00'},
  {'city': 'Iceland', 'country': 'Unknown', 'timezone': 'GMT+00:00'},
  {'city': 'Antananarivo', 'country': 'Indian', 'timezone': 'GMT+03:00'},
  {'city': 'Chagos', 'country': 'Indian', 'timezone': 'GMT+06:00'},
  {'city': 'Christmas', 'country': 'Indian', 'timezone': 'GMT+07:00'},
  {'city': 'Cocos', 'country': 'Indian', 'timezone': 'GMT+06:30'},
  {'city': 'Comoro', 'country': 'Indian', 'timezone': 'GMT+03:00'},
  {'city': 'Kerguelen', 'country': 'Indian', 'timezone': 'GMT+05:00'},
  {'city': 'Mahe', 'country': 'Indian', 'timezone': 'GMT+04:00'},
  {'city': 'Maldives', 'country': 'Indian', 'timezone': 'GMT+05:00'},
  {'city': 'Mauritius', 'country': 'Indian', 'timezone': 'GMT+04:00'},
  {'city': 'Mayotte', 'country': 'Indian', 'timezone': 'GMT+03:00'},
  {'city': 'Reunion', 'country': 'Indian', 'timezone': 'GMT+04:00'},
  {'city': 'Iran', 'country': 'Unknown', 'timezone': 'GMT+03:30'},
  {'city': 'Israel', 'country': 'Unknown', 'timezone': 'GMT+02:00'},
  {'city': 'Jamaica', 'country': 'Unknown', 'timezone': 'GMT-05:00'},
  {'city': 'Japan', 'country': 'Unknown', 'timezone': 'GMT+09:00'},
  {'city': 'Kwajalein', 'country': 'Unknown', 'timezone': 'GMT+12:00'},
  {'city': 'Libya', 'country': 'Unknown', 'timezone': 'GMT+02:00'},
  {'city': 'MET', 'country': 'Unknown', 'timezone': 'GMT+01:00'},
  {'city': 'MST', 'country': 'Unknown', 'timezone': 'GMT-07:00'},
  {'city': 'MST7MDT', 'country': 'Unknown', 'timezone': 'GMT-06:00'},
  {'city': 'BajaNorte', 'country': 'Mexico', 'timezone': 'GMT-07:00'},
  {'city': 'BajaSur', 'country': 'Mexico', 'timezone': 'GMT-07:00'},
  {'city': 'General', 'country': 'Mexico', 'timezone': 'GMT-06:00'},
  {'city': 'NZ', 'country': 'Unknown', 'timezone': 'GMT+13:00'},
  {'city': 'NZ-CHAT', 'country': 'Unknown', 'timezone': 'GMT+13:45'},
  {'city': 'Navajo', 'country': 'Unknown', 'timezone': 'GMT-06:00'},
  {'city': 'PRC', 'country': 'Unknown', 'timezone': 'GMT+08:00'},
  {'city': 'PST8PDT', 'country': 'Unknown', 'timezone': 'GMT-07:00'},
  {'city': 'Apia', 'country': 'Pacific', 'timezone': 'GMT+13:00'},
  {'city': 'Auckland', 'country': 'Pacific', 'timezone': 'GMT+13:00'},
  {'city': 'Bougainville', 'country': 'Pacific', 'timezone': 'GMT+11:00'},
  {'city': 'Chatham', 'country': 'Pacific', 'timezone': 'GMT+13:45'},
  {'city': 'Chuuk', 'country': 'Pacific', 'timezone': 'GMT+10:00'},
  {'city': 'Easter', 'country': 'Pacific', 'timezone': 'GMT-05:00'},
  {'city': 'Efate', 'country': 'Pacific', 'timezone': 'GMT+11:00'},
  {'city': 'Enderbury', 'country': 'Pacific', 'timezone': 'GMT+13:00'},
  {'city': 'Fakaofo', 'country': 'Pacific', 'timezone': 'GMT+13:00'},
  {'city': 'Fiji', 'country': 'Pacific', 'timezone': 'GMT+12:00'},
  {'city': 'Funafuti', 'country': 'Pacific', 'timezone': 'GMT+12:00'},
  {'city': 'Galapagos', 'country': 'Pacific', 'timezone': 'GMT-06:00'},
  {'city': 'Gambier', 'country': 'Pacific', 'timezone': 'GMT-09:00'},
  {'city': 'Guadalcanal', 'country': 'Pacific', 'timezone': 'GMT+11:00'},
  {'city': 'Guam', 'country': 'Pacific', 'timezone': 'GMT+10:00'},
  {'city': 'Honolulu', 'country': 'Pacific', 'timezone': 'GMT-10:00'},
  {'city': 'Johnston', 'country': 'Pacific', 'timezone': 'GMT-10:00'},
  {'city': 'Kanton', 'country': 'Pacific', 'timezone': 'GMT+13:00'},
  {'city': 'Kiritimati', 'country': 'Pacific', 'timezone': 'GMT+14:00'},
  {'city': 'Kosrae', 'country': 'Pacific', 'timezone': 'GMT+11:00'},
  {'city': 'Kwajalein', 'country': 'Pacific', 'timezone': 'GMT+12:00'},
  {'city': 'Majuro', 'country': 'Pacific', 'timezone': 'GMT+12:00'},
  {'city': 'Marquesas', 'country': 'Pacific', 'timezone': 'GMT-09:30'},
  {'city': 'Midway', 'country': 'Pacific', 'timezone': 'GMT-11:00'},
  {'city': 'Nauru', 'country': 'Pacific', 'timezone': 'GMT+12:00'},
  {'city': 'Niue', 'country': 'Pacific', 'timezone': 'GMT-11:00'},
  {'city': 'Norfolk', 'country': 'Pacific', 'timezone': 'GMT+12:00'},
  {'city': 'Noumea', 'country': 'Pacific', 'timezone': 'GMT+11:00'},
  {'city': 'Pago Pago', 'country': 'Pacific', 'timezone': 'GMT-11:00'},
  {'city': 'Palau', 'country': 'Pacific', 'timezone': 'GMT+09:00'},
  {'city': 'Pitcairn', 'country': 'Pacific', 'timezone': 'GMT-08:00'},
  {'city': 'Pohnpei', 'country': 'Pacific', 'timezone': 'GMT+11:00'},
  {'city': 'Ponape', 'country': 'Pacific', 'timezone': 'GMT+11:00'},
  {'city': 'Port Moresby', 'country': 'Pacific', 'timezone': 'GMT+10:00'},
  {'city': 'Rarotonga', 'country': 'Pacific', 'timezone': 'GMT-10:00'},
  {'city': 'Saipan', 'country': 'Pacific', 'timezone': 'GMT+10:00'},
  {'city': 'Samoa', 'country': 'Pacific', 'timezone': 'GMT-11:00'},
  {'city': 'Tahiti', 'country': 'Pacific', 'timezone': 'GMT-10:00'},
  {'city': 'Tarawa', 'country': 'Pacific', 'timezone': 'GMT+12:00'},
  {'city': 'Tongatapu', 'country': 'Pacific', 'timezone': 'GMT+13:00'},
  {'city': 'Truk', 'country': 'Pacific', 'timezone': 'GMT+10:00'},
  {'city': 'Wake', 'country': 'Pacific', 'timezone': 'GMT+12:00'},
  {'city': 'Wallis', 'country': 'Pacific', 'timezone': 'GMT+12:00'},
  {'city': 'Yap', 'country': 'Pacific', 'timezone': 'GMT+10:00'},
  {'city': 'Poland', 'country': 'Unknown', 'timezone': 'GMT+01:00'},
  {'city': 'Portugal', 'country': 'Unknown', 'timezone': 'GMT+00:00'},
  {'city': 'ROC', 'country': 'Unknown', 'timezone': 'GMT+08:00'},
  {'city': 'ROK', 'country': 'Unknown', 'timezone': 'GMT+09:00'},
  {'city': 'Singapore', 'country': 'Unknown', 'timezone': 'GMT+08:00'},
  {'city': 'Turkey', 'country': 'Unknown', 'timezone': 'GMT+03:00'},
  {'city': 'UCT', 'country': 'Unknown', 'timezone': 'GMT+00:00'},
  {'city': 'Alaska', 'country': 'US', 'timezone': 'GMT-08:00'},
  {'city': 'Aleutian', 'country': 'US', 'timezone': 'GMT-09:00'},
  {'city': 'Arizona', 'country': 'US', 'timezone': 'GMT-07:00'},
  {'city': 'Central', 'country': 'US', 'timezone': 'GMT-05:00'},
  {'city': 'East-Indiana', 'country': 'US', 'timezone': 'GMT-04:00'},
  {'city': 'Eastern', 'country': 'US', 'timezone': 'GMT-04:00'},
  {'city': 'Hawaii', 'country': 'US', 'timezone': 'GMT-10:00'},
  {'city': 'Indiana-Starke', 'country': 'US', 'timezone': 'GMT-05:00'},
  {'city': 'Michigan', 'country': 'US', 'timezone': 'GMT-04:00'},
  {'city': 'Mountain', 'country': 'US', 'timezone': 'GMT-06:00'},
  {'city': 'Pacific', 'country': 'US', 'timezone': 'GMT-07:00'},
  {'city': 'Samoa', 'country': 'US', 'timezone': 'GMT-11:00'},
  {'city': 'UTC', 'country': 'Unknown', 'timezone': 'GMT+00:00'},
  {'city': 'Universal', 'country': 'Unknown', 'timezone': 'GMT+00:00'},
  {'city': 'W-SU', 'country': 'Unknown', 'timezone': 'GMT+03:00'},
  {'city': 'WET', 'country': 'Unknown', 'timezone': 'GMT+00:00'},
  {'city': 'Zulu', 'country': 'Unknown', 'timezone': 'GMT+00:00'}
];